### ISSUE TITLE
No application and no parameters are used from classes matched by “class_mappings”

### ISSUE THREAD

**Issue by baby-gnu** [madduck/reclass#16]
Hello,

Making more tests on `class_mappings` I found that nodes matching (`minion2.baby-gnu.net` in the following example) do not use the `applications` nor the `parameters` of associated classes.

For example:

``` yaml
--- # /srv/salt/reclass-config.yml
class_mappings:
  - /^([^\/]+)\// zone-\\1
...
```

``` yaml
--- # /srv/salt/classes/default.yml
applications:
    - common
parameters:
    foo:
        - one: 1
        - two: 2
...
```

``` yaml
--- # /srv/salt/classes/zone-test.yml
applications:
  - develop
parameters:
  foo: from zone-test
...
```

``` yaml
--- # /srv/salt/node/minion1.baby-gnu.net.yml
classes:
  - default
parameters:
  foo: from reclass pillar of node
...
```

``` yaml
--- # /srv/salt/node/test/minion2.baby-gnu.net.yml
# empty
...
```

The inventory output is the following:

``` yaml
--- # reclass -b /srv/salt -i__reclass__:
  timestamp: Thu Dec 26 14:37:35 2013
applications:
  common:
  - minion1.baby-gnu.net
classes:
  default:
  - minion1.baby-gnu.net
  zone-test:
  - minion2.baby-gnu.net
nodes:
  minion1.baby-gnu.net:
    __reclass__:
      name: minion1.baby-gnu.net
      node: minion1.baby-gnu.net
      timestamp: Thu Dec 26 14:37:35 2013
      uri: yaml_fs:///srv/salt/nodes/minion1.baby-gnu.net.yml
    applications:
    - common
    classes:
    - default
    parameters:
      foo: from reclass pillar of node
  minion2.baby-gnu.net:
    __reclass__:
      name: minion2.baby-gnu.net
      node: test/minion2.baby-gnu.net
      timestamp: Thu Dec 26 14:37:35 2013
      uri: yaml_fs:///srv/salt/nodes/test/minion2.baby-gnu.net.yml
    applications: []
    classes:
    - zone-test
    parameters: {}
...
```

And the top file is the following:

``` yaml
--- #/usr/share/reclass/reclass-salt -b /srv/salt --top 
base:
  minion1.baby-gnu.net:
  - common
  minion2.baby-gnu.net: []
...
```

I was expecting `minion2.baby-gnu.net` to have:

``` yaml
applications:
  - develop
parameters:
  foo: from zone-test
```

Regards.
