### ISSUE TITLE
remove extra ./ in node name and uri

### ISSUE THREAD

**Issue by iluminite** [madduck/reclass#29]
I'm not sure where this `./` sneaks in, but it seems unnecessary and likely easy to remove. I can dig through the code to figure out where this is happening in `reclass.storage.yaml_fs`, but am in the middle of other things. This is mostly a reminder to myself, and a place for discussion if removing the ./ is not a good idea.

Here is an example as it is right now:

```
__reclass__:
  environment: ''
  name: localhost
  node: ./localhost
  timestamp: Sat Oct  4 17:55:54 2014
  uri: yaml_fs:///etc/reclass/nodes/./localhost.yml
```

I see this type of output as the goal of this ticket:

```
__reclass__:
  environment: ''
  name: localhost
  node: localhost
  timestamp: Sat Oct  4 17:55:54 2014
  uri: yaml_fs:///etc/reclass/nodes/localhost.yml
```
