### ISSUE TITLE
Question about reclass node definitions and dynamic parameters

### ISSUE THREAD

**Issue by shomodj** [madduck/reclass#49]
Hi all, 

I have a question about reclass node definitions and dynamic parameters,

lets say I have a class user.yml in classes directory:

```
classes:
  - ...
applications:
  - ...
parameters:
  user:
    username: foo
    shell: /bin/bash
    home_dir: /home/foo
```

but lets say this has to work on Debian and Mac, and under mac home_dir is /Users/foo,
not sure if jinja and grains work on reclass node definitions, don't think so.

But how would one solve this, it has to be in one class, and parameter has to be home_dir but the value is different based on the os_family grain?

Thanks,
Boris.
