### ISSUE TITLE
Allow variable substitution also on keys?

### ISSUE THREAD

**Issue by Sjd-Risca** [madduck/reclass#51]
I give you this example:
---------------
```yaml
pamaters:
  git:
    GH: git://github.com/Sjd-Risca
  salt:
    master:
      gitfs_remotes:
      - ${git:GH}/saltODOO.git:
        - root: odoo
        - mountpoint: salt://ODOO
      win_gitrepos:
      - ${git:GH}/salt-winrepo-ng.git
```
------------------
In this case only the secon variable subtitution (in which it is a parameter) works getting back:
      - git://github.com/Sjd-Risca/salt-winrepo-ng.git

Instead where the variable ${git:GH} is in the key I get back the string as it is, without substitution:
      - ${git:GH}/saltODOO.git:

Is this something expected or it should be expect to alway substitute?
